version: 0.2
phases:
  install:
    commands:
      - dotnet tool install -g Wyam.Tool
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - wyam -v
artifacts:
  files:
    - output/*